--Script para Excluir as TABELAS

-- DROP TABLE TB_PROJETO_MUSICAL:
    DROP TABLE TB_PROJETO_MUSICAL;
    
-- DROP TABLE TB_CARREIRA_SOLO:
    DROP TABLE TB_CARREIRA_SOLO;
    
-- DROP TABLE TB_BANDA:
    DROP TABLE TB_BANDA;
    
-- DROP TABLE TB_ALBUNS:
    DROP TABLE TB_ALBUNS;
    
-- DROP TABLE TB_FULL_LENGTH:
    DROP TABLE TB_FULL_LENGTH;
    
-- DROP TABLE TB_EP_SINGLE:
    DROP TABLE TB_EP_SINGLE;
    
-- DROP TABLE TB_TB_SPLIT:
    DROP TABLE TB_SPLIT;
    
-- DROP TABLE TB_MUSICO:
    DROP TABLE TB_MUSICO;
    
-- DROP TABLE TB_MUSICAS:
    DROP TABLE TB_MUSICAS;
    
-- DROP TABLE TB_INSTRUMENTO:
    DROP TABLE TB_INSTRUMENTO;
    
-- DROP TABLE TB_GENERO:
    DROP TABLE TB_GENERO;
    
-- DROP TABLE TB_LABEL:
    DROP TABLE TB_LABEL; 
    
-- DROP TABLE TB_MEMBROS:
    DROP TABLE TB_MEMBROS;
    
-- DROP TABLE TB_PROJETOMUSICAL_TEM_ALBUNS:
    DROP TABLE TB_PROJETOMUSICAL_TEM_ALBUNS;
    
-- DROP TABLE TB_GENERO_PERTENCE_PROJETOMUSICAL:
    DROP TABLE TB_GENERO_PERTENCE_PROJETOMUSICAL;
    
-- DROP TABLE TB_MUSICO_TEM_CARREIRASOLO:
    DROP TABLE TB_MUSICO_TEM_CARREIRASOLO;
    
-- DROP TABLE TB_MUSICO_TOCA_INSTRUMENTO:
    DROP TABLE TB_MUSICO_TOCA_INSTRUMENTO;    