-- Script de Criação de PKs, FKs etc...


-- Adicionando CONSTRAINTS CHAVES PRIMARIAS(PKs) PARA AS TABELAS:
-- CRIAÇÃO DE PK PARA PROJETO_MUSICAL:
    ALTER TABLE TB_PROJETO_MUSICAL ADD CONSTRAINT PK_PROJMUSICAL_IdProjeto PRIMARY KEY (IdProjeto);
    
-- CRIAÇÃO DE PK PARA CARREIRA_SOLO:
    ALTER TABLE TB_CARREIRA_SOLO ADD CONSTRAINT PK_CARREIRASOLO_IdProjeto PRIMARY KEY (IdProjeto);
    
-- CRIAÇÃO DE PK PARA BANDA:
    ALTER TABLE TB_BANDA ADD CONSTRAINT PK_BANDA_IdProjeto PRIMARY KEY (IdProjeto);

-- CRIAÇÃO DE PK PARA ALBUNS:
    ALTER TABLE TB_ALBUNS ADD CONSTRAINT PK_ALBUNS_IdAlbum PRIMARY KEY (IdAlbum);
    
-- CRIAÇÃO DE PK PARA FULL_LENGTH:
    ALTER TABLE TB_FULL_LENGTH ADD CONSTRAINT PK_FULLLENGTH_IdAlbum PRIMARY KEY (IdAlbum);

-- CRIAÇÃO DE PK PARA EP_SINGLE:
    ALTER TABLE TB_EP_SINGLE ADD CONSTRAINT PK_EPSINGLE_IdAlbum PRIMARY KEY (IdAlbum);
    
-- CRIAÇÃO DE PK PARA TB_SPLIT:
    ALTER TABLE TB_SPLIT ADD CONSTRAINT PK_SPLIT_IdAlbum PRIMARY KEY (IdAlbum);
    
-- CRIAÇÃO DE PK PARA MUSICO:
    ALTER TABLE TB_MUSICO ADD CONSTRAINT PK_MUSICO_IdMusico PRIMARY KEY (IdMusico);
    
-- CRIAÇÃO DE PK PARA MUSICAS:
    ALTER TABLE TB_MUSICAS ADD CONSTRAINT PK_MUSICAS_IdMusica PRIMARY KEY (IdMusica);
    
-- CRIAÇÃO DE PK PARA INSTRUMENTO:
    ALTER TABLE TB_INSTRUMENTO ADD CONSTRAINT PK_INSTRUMENTO_IdInst PRIMARY KEY (IdInstrumento);
    
-- CRIAÇÃO DE PK PARA GENERO:
    ALTER TABLE TB_GENERO ADD CONSTRAINT PK_GENERO_IdGen PRIMARY KEY (IdGenero);

-- CRIAÇÃO DE PK PARA TB_LABEL:
    ALTER TABLE TB_LABEL ADD CONSTRAINT PK_LABEL_IdLabel PRIMARY KEY (IdLabel);
    
-- CRIAÇÃO DE PK PARA MEMBROS:
    ALTER TABLE TB_MEMBROS ADD CONSTRAINT PK_MEMBROS_IdMembro PRIMARY KEY (IdMembro);
    
-- CRIAÇÃO DE PK PARA PROJETOMUSICAL_TEM_ALBUNS:
    ALTER TABLE TB_PROJETOMUSICAL_TEM_ALBUNS ADD CONSTRAINT PK_TEM_IdProjIdAlbum PRIMARY KEY (IdProjeto, IdAlbum);
    
-- CRIAÇÃO DE PK PARA GENERO_PERTENCE_PROJETOMUSICAL:
    ALTER TABLE TB_GENERO_PERTENCE_PROJETOMUSICAL ADD CONSTRAINT PK_PERTENCE_IdGenIdProj PRIMARY KEY (IdGenero, IdProjeto);
    

-- CRIAÇÃO DE PK PARA MUSICO_TEM_CARREIRASOLO
    ALTER TABLE TB_MUSICO_TEM_CARREIRASOLO ADD CONSTRAINT PK_TEM_IdMusIdCarSolo PRIMARY KEY (IdMusico,  IdProjeto);
    
-- CRIAÇÃO DE PK PARA MUSICO_TOCA_INSTRUMENTO
    ALTER TABLE TB_MUSICO_TOCA_INSTRUMENTO ADD CONSTRAINT PK_TOCA_IdMusIdInst PRIMARY KEY (IdMusico,  IdInstrumento);
    
    
-- Adicionando CONSTRAINTS CHAVES ESTRANGEIRAS(FKs) PARA AS TABELAS:   
-- CRIAÇÃO DE FK PARA PROJETO_MUSICAL:
    ALTER TABLE TB_PROJETO_MUSICAL ADD CONSTRAINT FK_PROJMUSICAL_IdLabel FOREIGN KEY (IdLabel) REFERENCES TB_LABEL; 
    
-- CRIAÇÃO DE FK PARA CARREIRA_SOLO:
    ALTER TABLE TB_CARREIRA_SOLO ADD CONSTRAINT FK_CARREIRASOLO_IdProjeto FOREIGN KEY (IdProjeto) REFERENCES TB_PROJETO_MUSICAL;

-- CRIAÇÃO DE FK PARA BANDA:
    ALTER TABLE TB_BANDA ADD CONSTRAINT FK_BANDA_IdProjeto FOREIGN KEY (IdProjeto) REFERENCES TB_PROJETO_MUSICAL;

-- CRIAÇÃO DE FK PARA ALBUNS:
    ALTER TABLE TB_ALBUNS ADD CONSTRAINT FK_ALBUNS_IdLabel FOREIGN KEY (IdLabel) REFERENCES TB_LABEL;

-- CRIAÇÃO DE FK PARA FULL_LENGTH:
    ALTER TABLE TB_FULL_LENGTH ADD CONSTRAINT FK_FULLLENGTH_IdAlbum FOREIGN KEY (IdAlbum) REFERENCES TB_ALBUNS;

-- CRIAÇÃO DE FK PARA EP_SINGLE:
    ALTER TABLE TB_EP_SINGLE ADD CONSTRAINT FK_EPSINGLE_IdAlbum FOREIGN KEY (IdAlbum)  REFERENCES TB_ALBUNS;

-- CRIAÇÃO DE FK PARA TB_SPLIT:
    ALTER TABLE TB_SPLIT ADD CONSTRAINT FK_SPLIT_IdAlbum FOREIGN KEY (IdAlbum) REFERENCES TB_ALBUNS;

-- CRIAÇÃO DE FK PARA MUSICAS:
    ALTER TABLE TB_MUSICAS ADD CONSTRAINT FK_MUSICAS_IdAlbum FOREIGN KEY (IdAlbum) REFERENCES TB_ALBUNS;

-- CRIAÇÃO DE FK PARA MEMBROS:
    ALTER TABLE TB_MEMBROS ADD CONSTRAINT FK_MEMBROS_IdProjeto FOREIGN KEY (IdProjeto) REFERENCES TB_PROJETO_MUSICAL;
    ALTER TABLE TB_MEMBROS ADD CONSTRAINT FK_MEMBROS_IdMusico FOREIGN KEY (IdMusico) REFERENCES TB_MUSICO;

-- CRIAÇÃO DE FK PARA PROJETOMUSICAL_TEM_ALBUNS:
    ALTER TABLE TB_PROJETOMUSICAL_TEM_ALBUNS ADD CONSTRAINT FK_TEM_IdProjeto FOREIGN KEY (IdProjeto) REFERENCES TB_PROJETO_MUSICAL;
    ALTER TABLE TB_PROJETOMUSICAL_TEM_ALBUNS ADD CONSTRAINT FK_TEM_IdAlbum FOREIGN KEY (IdAlbum) REFERENCES TB_ALBUNS;

-- CRIAÇÃO DE FK PARA GENERO_PERTENCE_PROJETOMUSICAL:
    ALTER TABLE TB_GENERO_PERTENCE_PROJETOMUSICAL ADD CONSTRAINT FK_PERTENCE_IdGenero FOREIGN KEY (IdGenero) REFERENCES TB_GENERO;
    ALTER TABLE TB_GENERO_PERTENCE_PROJETOMUSICAL ADD CONSTRAINT FK_PERTENCE_IdProjeto FOREIGN KEY (IdProjeto) REFERENCES TB_PROJETO_MUSICAL;

-- CRIAÇÃO DE FK PARA MUSICO_TEM_CARREIRASOLO:
    ALTER TABLE TB_MUSICO_TEM_CARREIRASOLO ADD CONSTRAINT FK_TEM_IdMusico FOREIGN KEY (IdMusico) REFERENCES TB_MUSICO;
    ALTER TABLE TB_MUSICO_TEM_CARREIRASOLO ADD CONSTRAINT FK_TEM_IdProjeto FOREIGN KEY (IdProjeto) REFERENCES TB_CARREIRA_SOLO;

-- CRIAÇÃO DE FK PARA MUSICO_TOCA_INSTRUMENTO:
    ALTER TABLE TB_MUSICO_TOCA_INSTRUMENTO ADD CONSTRAINT FK_TOCA_IdMusico FOREIGN KEY (IdMusico) REFERENCES TB_MUSICO;
    ALTER TABLE TB_MUSICO_TOCA_INSTRUMENTO ADD CONSTRAINT FK_TOCA_IdInstrumento FOREIGN KEY (IdInstrumento) REFERENCES TB_INSTRUMENTO;
    
    
-- Adicionando CONSTRAINTS CHECKs(CKs) PARA AS TABELAS:   
-- CRIAÇÃO DE CHECK PARA PROJETO_MUSICAL:
    ALTER TABLE TB_PROJETO_MUSICAL ADD CONSTRAINT CK_PROJMUSICAL_TipoProj CHECK (TipoProjeto in ('B', 'S')); -- BANDA OU SOLO

-- CRIAÇÃO DE CHECK PARA CARREIRA_SOLO:
    ALTER TABLE TB_CARREIRA_SOLO ADD CONSTRAINT CK_CARREIRASOLO_MultiInst CHECK (MultiInstrumentista in ('S', 'N'));

-- CRIAÇÃO DE CHECK PARA FULL_LENGTH:
    ALTER TABLE TB_FULL_LENGTH ADD CONSTRAINT CK_FULLLENGTH_EhConceitual CHECK (EhConceitual in ('S', 'N'));
    ALTER TABLE TB_FULL_LENGTH ADD CONSTRAINT CK_FULLLENGTH_PossuiBonusTrack CHECK (PossuiBonusTrack in ('S', 'N'));

-- CRIAÇÃO DE CHECK PARA EP_SINGLE:
    ALTER TABLE TB_EP_SINGLE ADD CONSTRAINT CK_EPSINGLE_EhProm CHECK (EhPromocional in ('S', 'N'));
    ALTER TABLE TB_EP_SINGLE ADD CONSTRAINT CK_EPSINGLE_ContemCover CHECK (ContemCover in ('S', 'N'));
    ALTER TABLE TB_EP_SINGLE ADD CONSTRAINT CK_EPSINGLE_VersaoLim CHECK (VersaoLimitada in ('S', 'N'));

-- CRIAÇÃO DE CHECK PARA MUSICO:
    ALTER TABLE TB_MUSICO ADD CONSTRAINT CK_MUSICO_Genero CHECK (Genero in ('M', 'F', 'O'));

-- CRIAÇÃO DE CHECK PARA TB_LABEL:
    ALTER TABLE TB_LABEL ADD CONSTRAINT CK_LABEL_PossuiLojaOnline CHECK (PossuiLojaOnline in ('S', 'N'));

